"""Add precio_anual to Plan model

Revision ID: 74c93d28519a
Revises: 957d4a6cf1bc
Create Date: 2025-08-18 11:14:23.975970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c93d28519a'
down_revision = '957d4a6cf1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_anual', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planes', schema=None) as batch_op:
        batch_op.drop_column('precio_anual')

    # ### end Alembic commands ###
