"""add indices and constraints

Revision ID: 8de89f5e2271
Revises: 3b56d7741c81
Create Date: 2025-08-15 18:49:42.528687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de89f5e2271'
down_revision = '3b56d7741c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresas_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresas_plan'), ['plan'], unique=False)

    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servicios_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_servicios_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_servicios_nombre'), ['nombre'], unique=True)

    with op.batch_alter_table('suscripciones', schema=None) as batch_op:
        batch_op.create_index('idx_empresa_estado', ['empresa_id', 'estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_suscripciones_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suscripciones_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_suscripciones_servicio_id'), ['servicio_id'], unique=False)
        batch_op.create_unique_constraint('uk_empresa_servicio_activo', ['empresa_id', 'servicio_id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_rol'), ['rol'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_rol'))
        batch_op.drop_index(batch_op.f('ix_usuarios_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_creado_en'))

    with op.batch_alter_table('suscripciones', schema=None) as batch_op:
        batch_op.drop_constraint('uk_empresa_servicio_activo', type_='unique')
        batch_op.drop_index(batch_op.f('ix_suscripciones_servicio_id'))
        batch_op.drop_index(batch_op.f('ix_suscripciones_estado'))
        batch_op.drop_index(batch_op.f('ix_suscripciones_empresa_id'))
        batch_op.drop_index('idx_empresa_estado')

    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servicios_nombre'))
        batch_op.drop_index(batch_op.f('ix_servicios_creado_en'))
        batch_op.drop_index(batch_op.f('ix_servicios_activo'))

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_plan'))
        batch_op.drop_index(batch_op.f('ix_empresas_estado'))
        batch_op.drop_index(batch_op.f('ix_empresas_creado_en'))

    # ### end Alembic commands ###
