"""Add Plan model and relationship with Servicio

Revision ID: 957d4a6cf1bc
Revises: 8de89f5e2271
Create Date: 2025-08-18 08:32:57.962678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957d4a6cf1bc'
down_revision = '8de89f5e2271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio_mensual', sa.Float(), nullable=False),
    sa.Column('seleccionado', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planes_servicios',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['planes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('plan_id', 'servicio_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planes_servicios')
    op.drop_table('planes')
    # ### end Alembic commands ###
