"""convert_planes_servicios_to_model_with_cantidad

Revision ID: 9866b3dfd804
Revises: a1a29c03a38c
Create Date: 2025-11-20 16:13:52.007102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9866b3dfd804'
down_revision = 'a1a29c03a38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planes_servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planes_servicios', schema=None) as batch_op:
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
