"""add_descripcion_to_plan

Revision ID: a1a29c03a38c
Revises: e8f4a2c1d9b3
Create Date: 2025-10-20 18:46:11.210837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a29c03a38c'
down_revision = 'e8f4a2c1d9b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planes', sa.Column('descripcion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planes', 'descripcion')
    # ### end Alembic commands ###
