"""add_descripcion_to_plan"""add_descripcion_to_plan



Revision ID: a1a29c03a38cRevision ID: a1a29c03a38c

Revises: e8f4a2c1d9b3Revises: e8f4a2c1d9b3

Create Date: 2025-10-20 18:46:11.210837Create Date: 2025-10-20 18:46:11.210837



""""""

from alembic import opfrom alembic import op

import sqlalchemy as saimport sqlalchemy as sa



# revision identifiers, used by Alembic.# revision identifiers, used by Alembic.

revision = 'a1a29c03a38c'revision = 'a1a29c03a38c'

down_revision = 'e8f4a2c1d9b3'down_revision = 'e8f4a2c1d9b3'

branch_labels = Nonebranch_labels = None

depends_on = Nonedepends_on = None





def upgrade():def upgrade():

    # Agregar campo descripcion a la tabla planes    # Agregar campo descripcion a la tabla planes

    op.add_column('planes', sa.Column('descripcion', sa.Text(), nullable=True))    op.add_column('planes', sa.Column('descripcion', sa.Text(), nullable=True))



    with op.batch_alter_table('suscripciones', schema=None) as batch_op:

def downgrade():        batch_op.alter_column('plan_id',

    # Eliminar campo descripcion de la tabla planes               existing_type=mysql.INTEGER(display_width=11),

    op.drop_column('planes', 'descripcion')               nullable=False)

        batch_op.alter_column('periodo',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='mensual o anual',
               existing_nullable=True)
        batch_op.alter_column('precio_pagado',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='Precio al momento de la suscripción',
               existing_nullable=True)
        batch_op.alter_column('creado_en',
               existing_type=mysql.DATETIME(),
               server_default=None,
               nullable=False)
        batch_op.alter_column('creado_por',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='ID del admin que creó la suscripción',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_suscripcion_plan'))
        batch_op.create_index(batch_op.f('ix_suscripciones_fecha_fin'), ['fecha_fin'], unique=False)
        batch_op.create_index(batch_op.f('ix_suscripciones_plan_id'), ['plan_id'], unique=False)
        batch_op.create_foreign_key(None, 'usuarios', ['creado_por'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_usuarios_empresa_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_usuarios_empresa_id'), ['empresa_id'], unique=True)

    with op.batch_alter_table('suscripciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_suscripciones_plan_id'))
        batch_op.drop_index(batch_op.f('ix_suscripciones_fecha_fin'))
        batch_op.create_index(batch_op.f('idx_suscripcion_plan'), ['plan_id'], unique=False)
        batch_op.alter_column('creado_por',
               existing_type=mysql.INTEGER(display_width=11),
               comment='ID del admin que creó la suscripción',
               existing_nullable=True)
        batch_op.alter_column('creado_en',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               nullable=True)
        batch_op.alter_column('precio_pagado',
               existing_type=mysql.FLOAT(),
               comment='Precio al momento de la suscripción',
               existing_nullable=True)
        batch_op.alter_column('periodo',
               existing_type=mysql.VARCHAR(length=20),
               comment='mensual o anual',
               existing_nullable=True)
        batch_op.alter_column('plan_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('planes', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('1'),
               existing_nullable=False)

    # ### end Alembic commands ###
